# vim: set ft=yaml ts=2 expandtab:
---

- name: crond is absent
  package:
    name:
    - "{{ crond_package_absent }}"
    - "{{ crond_package }}"
    - "{{ anacron_package }}"
    state: absent

...
