# vim: set ft=yaml ts=2 expandtab:
---

- name: crond is present
  package:
    name: "{{ crond_package }}"
    state: present

- name: anacron is present/absent
  package:
    name: "{{ anacron_package }}"
    state: "{{ 'present' if anacron else 'absent' }}"

- name: crond is started
  service:
    name: crond
    state: started
    enabled: true

...
