# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 10 * * 6'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - fedora33
        - fedora34
        - centos8stream
        - centos7
        - centos8
        - alma8
        - debian9
        - debian10
        - ubuntu-16.04
        - ubuntu-18.04
        - ubuntu-20.04

        ansible_version:
        - '2.9'
        - '2.10'

        include:

        - target: fedora33
          distribution: fedora
          version: 33

        - target: fedora34
          distribution: fedora
          version: 34

        - target: centosstream8
          distribution: centos
          registry: "quay.io/centos/"
          version: stream8
          test_molecule: true
          test_controlnode: true

        - target: centos7
          distribution: centos
          version: 7

        - target: centos8
          distribution: centos
          version: 8

        - target: alma8
          distribution: almalinux
          registry: "docker.io/almalinux/"
          version: 8
          test_molecule: true
          test_controlnode: true

        - target: debian9
          distribution: debian
          version: stretch

        - target: debian10
          distribution: debian
          version: buster

        - target: ubuntu-16.04
          distribution: ubuntu
          version: xenial

        - target: ubuntu-18.04
          distribution: ubuntu
          version: bionic

        - target: ubuntu-20.04
          distribution: ubuntu
          version: focal

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/cron

    steps:

    - name: checkout collection ansible
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/cron

    # note: this uses ansible-galaxy from preinstalled ansible (2.10)
    #
    - name: install mafalb.ansible
      run: ansible-galaxy collection install mafalb.ansible

    # note: this uses ansible-playbook from system ansible
    #
    - name: install molecule
      run: |
        sudo apt install ansible
        /usr/bin/ansible-playbook -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=$ANSIBLE_VERSION -t all,debug

    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible ${{ matrix.ansible_version }}"

    - name: molecule tests
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test

...
